In [1]:
import numpy as np

1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
arr=np.array([5,6,7,8,9])

In [3]:
arr

array([5, 6, 7, 8, 9])

In [5]:
np.vander(arr,4) #By default increasing is equal to False

array([[125,  25,   5,   1],
       [216,  36,   6,   1],
       [343,  49,   7,   1],
       [512,  64,   8,   1],
       [729,  81,   9,   1]])

In [7]:
np.vander(arr,4,increasing=True)

array([[  1,   5,  25, 125],
       [  1,   6,  36, 216],
       [  1,   7,  49, 343],
       [  1,   8,  64, 512],
       [  1,   9,  81, 729]])

In [32]:
#Custom Implementation
def custom_vander(num_arr,n,asc_bool):
    #new_arr=np.empty([len(num_arr),n],dtype=float)
    new_arr=[]
    #print(new_arr)
    for i in range(n):
        tmp_arr=[]
        if(asc_bool):
            for j in range(n):
                tmp_arr.append(pow(num_arr[i],j)) #np.vander(arr,4)
        else:
            for j in range(n-1,-1,-1):
                tmp_arr.append(pow(num_arr[i],j))
        new_arr.append(tmp_arr)
    return np.array(new_arr)

In [33]:
custom_vander(arr,4,True)

array([[  1,   5,  25, 125],
       [  1,   6,  36, 216],
       [  1,   7,  49, 343],
       [  1,   8,  64, 512]])

In [34]:
custom_vander(arr,4,False)

array([[125,  25,   5,   1],
       [216,  36,   6,   1],
       [343,  49,   7,   1],
       [512,  64,   8,   1]])

2. Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [45]:
def avg_moving(arr,window):
    lavg=[]
    n=len(arr)
    k=window
    t=n-k+1
    #print(type(arr))
    for i in range(t):
        tmp_arr=[]
        tmp_arr=arr[i:i+k]
        tmp_avg=sum(tmp_arr)/k
        lavg.append(round(tmp_avg,2))
    #mavg=sum(lavg)/len(lavg)
    return lavg

In [46]:
avg_moving([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]